version: "3.9"

services:
  app:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=db
      - DB_USER=root
      - DB_PASSWORD=pass
      - REDIS_QUEUE_HOST=redis
      - REDIS_QUEUE_PORT=6379
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=root
      - RABBITMQ_PASS=pass
      - DISCROD_CLIENT_ID=abc
      - DISCORD_BOT_TOKEN=abc
      - DISCORD_TRY_NOW_CALLBACK_URI=abc
      - DISCORD_LOGIN_CALLBACK_URI=abc
      - DISCORD_CONNECT_GUILD_CALLBACK_URI=abc
      - JWT_SECRET=abc
      - JWT_ACCESS_EXPIRATION_MINUTES=999
      - JWT_REFRESH_EXPIRATION_DAYS=90
      - JWT_DISCORD_REFRESH_EXPIRATION_DAYS=90
      - FRONTEND_URL=abc
      - NOTION_API_KEY=abc
      - NOTION_DATABASE_ID=abc
    volumes:
      - ./coverage:/project/coverage
    depends_on:
      - redis
      - mongo
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass